### ISSUE TITLE
Yahoo Groups can start with a hyphen which causes problems when parsing command line

### ISSUE THREAD

**Issue by PaulWebster** [ArchiveTeam/yahoo-group-archiver#41]
Yahoo allowed groups to be created that start with a hyphen (minus sign) ... a feature that has been used in a small number of groups.
This can cause a problem when the command line is parsed since the group name is one of the fields on the command line and it can be interpreted as a parameter instead.

One way around this is to place the group name at the end of the parameter list but prefix it with "-- " however, this needs to be verified as working under Windows and when invoked by pipeline.py

If this works - then solution is to update pipeline.py to invoke this way and add documentation for people who are running yahoo.py by hand.

**Comment by lennier1** [comment]
markedL fixed this a little while ago.
